### ISSUE TITLE
documentation not installed?

### ISSUE THREAD

**Issue by bremner** [shriram/smol#27]
```
% raco pkg show -l smol
Installation-wide:
 [none]
User-specific for installation "8.7":
 Package[*=auto]    Checksum                                    Source
 smol*              da99591c7c4bb58ece6a1c935d95fbd2d64685b1    (url "https://github.com/shriram/smol.git")
```

If I bring up the main documentation page either via "raco doc" or from drracket, I can see some installed packages but not smol (or stacker, fwiw).

Do I need to do something special to force the documentation to install?

**Comment by shriram** [comment]
Hi @LuKC1024 — did you see the above?

**Comment by LuKuangChen** [comment]
I would consider this bug perhaps specific to a particular version of Racket and `#lang smol` because

* `% raco doc smol` works well in my environment as of now.
*  I never hear the same feedback from other people. In particular, CS173 TAs often consult the smol documentation, but never complaint about similar problems.

**Comment by bremner** [comment]
KC Lu ***@***.***> writes:

> I would consider this bug perhaps specific to a particular version of Racket and `#lang smol`, and probably has disappear.
>
> * `% raco doc smol` works well in my environment as of now.
> *  I never hear the same feedback from other people. In particular, CS173 TAs often consult the smol documentation, but never complaint about similar problems.
>

Hi KC;

I just confirmed it works for me currently (with racket 8.14 and current
smol). So I agree the bug can be closed.

d
